### ISSUE TITLE
As a user, I want to be able to login so that I can access my account

### ISSUE THREAD

**Issue by gfdb** [gfdb/soen390#1]

**Comment by liuwei-tianshu** [comment]
Give more detailed description about the notion "user" (actually, the name "user" is not good.).

The user should be defined accurately. 

It seems that the user here covers patients/doctors/admin.
Yes, patients/doctors/admin have the "same" function of login indeed. 
But this is not good in the document. 

In other places, the user ONLY refers to patients. 
So, people will definitely get confused when he see the term "user". 
For example, a developer in you team may implement the login function for patients/doctors/admin. But the tester just test the login function for patients.

**Comment by liuwei-tianshu** [comment]
My suggestions 
1. As a patient/non-patient (if your application has no "no-patient", delete the non-patient), I want to be able to login so that ...
2. As a doctor/healthy ... I want to be able to login so that ...

I am not sure, but they may have different actions during the login. Just like shoppers and sellers, they should have different login websites.

**Comment by gfdb** [comment]
@liuwei-tianshu In this case, the notion of User is in reference to Users in general since login is a feature that all users are going to need. As discussed in the meeting, there will be two different websites. I think the best option will be to have one login page for all users and depending on user privilege redirect them to their respective websites. As a result, I think having this one issue for both cases makes sense, what do you think?

P.S. Is it okay for us to use "Users" in cases like this where it applies to anyone using the web app?

**Comment by liuwei-tianshu** [comment]
> I think the best option will be to have one login page for all users and depending on user privilege redirect them to their respective websites. 

One login page is OK. 

> As a result, I think having this one issue for both cases makes sense, what do you think?

Perfect. Much clear. 


> P.S. Is it okay for us to use "Users" in cases like this where it applies to anyone using the web app?

It is OK to use "Users" in this situation like login logout signup. For other situations, please use "patients, doctors, .etc"
