### ISSUE TITLE
As a health official i want to notify people who have been in contact with covid-19 patients so people can know when to get tested and be careful

### ISSUE THREAD

**Issue by dionisiapoulios** [gfdb/soen390#112]

**Comment by davrine** [comment]
if user has covid and comes into contact with user that doesnt have covid notify that user. @liuwei-tianshu is this acceptable implementation of  this feature

**Comment by liuwei-tianshu** [comment]
> if user has covid and comes into contact with user that doesnt have covid notify that user. @liuwei-tianshu is this acceptable implementation of this feature

I do not see any problems. You can make the decision on the feature.
