### ISSUE TITLE
As a Patient I want to be able to sign up so that an account is created for me.

### ISSUE THREAD

**Issue by gfdb** [gfdb/soen390#12]
Sign up page (frontend) #39 
Sign up page (backend) #40

Depends on completion of #41

**Comment by gfdb** [comment]
@liuwei-tianshu Should I assign the story to anyone or can I leave it with no assignees since I already assigned the sub tasks to various team members? or should I assign the story to the same people as I assigned the subtasks to?

**Comment by liuwei-tianshu** [comment]
> @liuwei-tianshu Should I assign the story to anyone or can I leave it with no assignees since I already assigned the sub tasks to various team members? or should I assign the story to the same people as I assigned the subtasks to?

It is better to assign the story to the same people.

So, the project manager can view that every story is [under control](https://github.com/users/gfdb/projects/1/views/5). (the assignee, the status, the due time for each story)

**Comment by liuwei-tianshu** [comment]
> 



> Sign up page (frontend) #39 Sign up page (backend) #40
> 
> Depends on completion of #41

Greate job to link user stories to tasks! 

Or you can just put the details (backend, frontend ... ) of tasks in the description of this issue (user story). Both frontend developers and backend developers will concentrate on this issue at the same time. So, you won't see too many "sub tasks". 

You can choose the way you preferred. Both of them are OK.
