### ISSUE TITLE
The patient list page crashes

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#158]
Reproduce steps:
1 sign in as a doctor,   email: doctor00010@gmail.com password: 123456
2 click the patient menu
3 the page crashes

The doctor can not use any features regarding patients. So, it is a serious bug with critical priority.

![no patients list](https://user-images.githubusercontent.com/55549554/159580081-8d9528ad-3b06-48df-84b9-3448d5483e8c.gif)

![20220322173146](https://user-images.githubusercontent.com/55549554/159580157-bab4187a-08ba-44c6-91e9-5e4620da22d2.jpg)

**Comment by liuwei-tianshu** [comment]
Please assign one/two/three QAs to test all workflows of the system.

I am afraid the system is **unusable** because there are still many bugs in the system.
Please test the system carefully and fix serious bugs ASAP.

After the bugs are fixed, let the QA varify them again. Only the QA in your team can close the bugs.

**Comment by davrine** [comment]
@mohamad-elchanati  should i close this
