### ISSUE TITLE
Incorrect link for home menu when loged in as a doctor

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#159]
Reproduce steps:
1 log in as a doctor
2 click the home menu
3 it goes to the wrong page instead of the home page for doctors. 

![incorrect like of home page](https://user-images.githubusercontent.com/55549554/159581664-65aa4f14-5aab-43f3-a071-943b722e1a3f.gif)

This is the home page for doctors. After clicking the home menu bar, it should stay in this page. Otherwise, the doctor can not go back to the doctor portal.
![20220322175013](https://user-images.githubusercontent.com/55549554/159582209-55895e2e-e91f-473d-80e6-fcbfe47bf36a.jpg)

**Comment by liuwei-tianshu** [comment]
1 Perhaps you can refer to the demo site of Solidus on GitHub: https://github.com/solidusio/solidus#demo
Actually, all of these systems are similar even they are in different domains. You can find a lot of these systems on GitHub by searching: eCommerce, CRM, ERP, forum ...

2 I was wondering you can let someone who is not familiar with it try to use the system. I believe there will be more defects be found by real clients.

3 Also, please provide a simple description of how to use it on README. People may do not understand what is the patient portal or admin portal. They may also do not understand how to use the patient portal in a mobile phone browser or in chrome.

4 **In a word, please test it more by QAs.**

5 @gfdb Please assign all of these bugs to the corresponding developers.
Please also assign all of these bugs to QAs to verify and close.

I just assigned them to the Project Manager because I do not know who are the QAs.

**Comment by davrine** [comment]
@liuwei-tianshu  please refer to issue #161
