### ISSUE TITLE
The input box of email address and password is too narrow when login as a patient

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#165]
Reproduce steps:
login as a patient, the input is too narrow.

As this login page is used for both patients and doctors, it needs to be compatible with both mobile browsers and desktop browsers. Maybe you need to modify the CSS or use Bootstrap to solve it. The Bootstrap is easy to use.

Low priority because it can not show the full email address and it affects the usability of the applications.

![20220324191703](https://user-images.githubusercontent.com/55549554/160025281-982869ce-649a-4155-86b8-6c483b1129e4.jpg)

**Comment by davrine** [comment]
@maritabrichan  is this closed now?

**Comment by maritabrichan** [comment]
@liuwei-tianshu @davrine This was fixed and pushed to main this morning. Please refer to #161

<img width="376" alt="Screen Shot 2022-03-24 at 8 07 14 PM" src="https://user-images.githubusercontent.com/60407502/160029538-4a9882c6-772a-4f5d-8ea5-1cef1f2363c3.png">

**Comment by liuwei-tianshu** [comment]
@maritabrichan  Perfect! You can close any bug report directly after verifying it.

**Comment by liuwei-tianshu** [comment]
Please deploy the main branch online frequently.
