### ISSUE TITLE
Defects on layout

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#166]
![layout](https://user-images.githubusercontent.com/55549554/160028166-dee59a8d-d6a2-4d07-997f-bbcefe3de141.jpg)
![cancel](https://user-images.githubusercontent.com/55549554/160028170-5edbbce5-2a69-4d9f-bd32-9e6f49bbf7fd.jpg)

**Comment by gfdb** [comment]
@liuwei-tianshu I fixed the cancel button but I am not sure what you would like us to do for the UI on the edit profile page. Should we completely redo it?

**Comment by liuwei-tianshu** [comment]
@gfdb For bugs with high priority, they must be fixed.
For other bugs, it depends on your team. You can make the decision about that according to the progress and teammates.

The only goal of this bug report is to show your teammates how to act as QA. I really think your system needs more testing by the QA. **The QA in your team will follow this "template of bug report" and report more bugs.**

For the QA, the only work he/she needs to do is to report every bug/defect. After that, your team will decide which bugs to fix and how to fix them. Just like the functionalities, the bugs can not be all fixed. You need to make the trade-off. However, you need to report bugs as many as you can first. Otherwise, there is no trade-off at all.

**Comment by gfdb** [comment]
@liuwei-tianshu Okay, got it.
