### ISSUE TITLE
The patient can not view his symptoms and diary

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#167]
Possible solution:
add a new page to show the history of symptoms and diary for a patient
in somewhere like the menu, provide a link to that page.

It has a high priority because it is an important feature of the app. 

![symptoms](https://user-images.githubusercontent.com/55549554/160028508-3232f975-11c6-427c-9468-df78bb5be465.jpg)

**Comment by liuwei-tianshu** [comment]
Also, the profile only represents basic information. 

It is better to separate the profile and "symptoms and status" into two pages.

The end-user needs to update his symptoms and diary every day. But he does not need to update the profile every day. It may make the end-user confused. Just my personal opinion. low priority

**Comment by davrine** [comment]
@liuwei-tianshu  The history feature hasn't been implemented yet its not a bug

**Comment by maritabrichan** [comment]
This is being implemented in the issue #122
