### ISSUE TITLE
[bug] Elements not aligned

### ISSUE THREAD

**Issue by lealakkis** [gfdb/soen390#189]
Steps to Reproduce
Login
try to edit profile

Actual
input boxed are not aligned
<img width="1383" alt="Screen Shot 2022-03-29 at 8 20 27 AM" src="https://user-images.githubusercontent.com/68018507/160609998-5c11c0d2-e8e4-4d29-ab73-bb015c5287f4.png">

Expected
Boxed should all be aligned 
Additional Comments

**Comment by dionisiapoulios** [comment]
This is no longer an issue.
