### ISSUE TITLE
Create / Refine User Stories Backlog on Github Issues

### ISSUE THREAD

**Issue by liuwei-tianshu** [gfdb/soen390#3]

**Comment by liuwei-tianshu** [comment]
@gfdb Please assign this task to whom it may concern, then each task could be finished by certain teammate
a project manager can use tasks to monitor the progress

**Comment by gfdb** [comment]
@liuwei-tianshu All user stories have been created. Refinement still has to be done as well as replacing the "User" to something that is more accurately defined for the stories that use the term.
