### ISSUE TITLE
As a Patient I want to be able to customize my status so that when I've been diagnosed with covid I can update the info accordingly.

### ISSUE THREAD

**Issue by gfdb** [gfdb/soen390#33]
I would like my status to be automatically updated to "patient" or allow for me to manually change my status when I've been diagnosed with covid.

**Comment by davrine** [comment]
## Description 
Back end for all of edit profile every field on edit profile page

**Comment by david-roper** [comment]
This role will be instead shifted to doctors and/or health officials.
