### ISSUE TITLE
Write backend code for Patient sign up page

### ISSUE THREAD

**Issue by gfdb** [gfdb/soen390#40]
In order for the sign up page to function properly the code for the backend needs to be written.
Things to do:
- Create the route that will render the sign up page
- inside the route include form logic that validates user input (eg. if password and confirm password match)

Subtask of #12

**Comment by liuwei-tianshu** [comment]
If you have no idea about the hosting and database. 

You can try to use free clouds such as [Amazon EC2(host for backend code) and Amazon RDS(host for the database)](https://aws.amazon.com/free/?nc2=h_ql_pr_ft). You will develop the code and run the project locally, installing the server like tomcat and databases like MySQL on your own computer. After debugging locally, you can deploy the project to the cloud with SMALL changes.

There are other alternatives like google cloud which also provides a free tire. It is up to your team.
